export const APP_CONFIG = {
  VERSION: '2.2.0-void-edition',
  IS_DEMO: false,
  GITHUB_REPO: 'devcitystudio/stellar-forge',
};

export const SFX = {
  CLICK: 'click',
  UPGRADE: 'upgrade',
  UNLOCK: 'unlock',
  ERROR: 'error'
};

export const ACHIEVEMENTS = [
  { id: 'spark_genesis', name: 'Spark of Genesis', description: 'Generate your first 1,000 Energy.', condition: (s) => s.resources.energy.totalEarned >= 1000, reward: '10% Click Bonus' },
  { id: 'matter_weaver', name: 'Matter Weaver', description: 'Synthesize 5,000 Matter.', condition: (s) => s.resources.matter.totalEarned >= 5000, reward: 'Unlock Quantum Realm' },
  { id: 'data_hoarder', name: 'Data Hoarder', description: 'Process 10,000 Data.', condition: (s) => s.resources.data.totalEarned >= 10000, reward: 'Passive Boost' },
  { id: 'dedicated_captain', name: 'Dedicated Captain', description: 'Play for 30 minutes.', condition: (s) => s.playTime >= 1800, reward: 'Visual Theme' },
  { id: 'click_frenzy', name: 'Click Frenzy', description: 'Perform 1,000 manual clicks.', condition: (s) => (s.stats?.clicks || 0) >= 1000, reward: 'Auto-Clicker Prototype' },
  { id: 'void_walker', name: 'Void Walker', description: 'Perform your first Prestige reset.', condition: (s) => s.prestigeCount > 0, reward: 'Unlocks Void Upgrades' }
];

export const WORLDS = [
  {
    id: 'prime',
    name: 'Stellar Forge',
    description: 'The cradle of existence. Synthesize basic matter and energy.',
    color: 'blue',
    primaryResource: 'energy',
    visibleResources: ['energy', 'matter', 'data', 'stardust'],
    bgGradient: 'radial-gradient(circle at center, #1e3a8a 0%, #020617 80%)',
    unlockReq: { resource: 'energy', amount: 0 }
  },
  {
    id: 'quantum',
    name: 'Quantum Realm',
    description: 'A sub-atomic plane where probability reigns supreme.',
    color: 'purple',
    primaryResource: 'quarks',
    visibleResources: ['quarks', 'matter'],
    bgGradient: 'radial-gradient(circle at center, #581c87 0%, #020617 80%)',
    unlockReq: { resource: 'matter', amount: 100000 }
  },
  {
    id: 'chronos',
    name: 'Chronos Expanse',
    description: 'The river of time flows backward here.',
    color: 'emerald',
    primaryResource: 'time',
    visibleResources: ['time', 'data'],
    bgGradient: 'radial-gradient(circle at center, #064e3b 0%, #020617 80%)',
    unlockReq: { resource: 'data', amount: 500000 }
  },
  {
    id: 'aether',
    name: 'Aetherial Plane',
    description: 'A spiritual dimension of pure magical potential.',
    color: 'cyan',
    primaryResource: 'aether',
    visibleResources: ['aether', 'stardust'],
    bgGradient: 'radial-gradient(circle at center, #0891b2 0%, #020617 80%)',
    unlockReq: { resource: 'stardust', amount: 5000 }
  },
  {
    id: 'void',
    name: 'The Void',
    description: 'The space between universes. Reset here to gain Cosmic Power.',
    color: 'red',
    primaryResource: 'entropy',
    visibleResources: ['entropy', 'energy'],
    bgGradient: 'radial-gradient(circle at center, #7f1d1d 0%, #000000 90%)',
    unlockReq: { resource: 'energy', amount: 1000000000 }
  }
];

export const INITIAL_STATE = {
  currentWorld: 'prime',
  unlockedWorlds: ['prime'],
  unlockedAchievements: [],
  logs: [{ id: 1, text: "System Initialized. Awaiting Input.", type: 'info' }],
  stats: { clicks: 0, cometsClicked: 0, totalResets: 0 },
  prestigeCount: 0,
  resources: {
    energy: { id: 'energy', name: 'Energy', amount: 0, totalEarned: 0, symbol: '⚡' },
    matter: { id: 'matter', name: 'Matter', amount: 0, totalEarned: 0, symbol: '⚛️' },
    data: { id: 'data', name: 'Data', amount: 0, totalEarned: 0, symbol: '💾' },
    stardust: { id: 'stardust', name: 'Stardust', amount: 0, totalEarned: 0, symbol: '✨' },
    quarks: { id: 'quarks', name: 'Quarks', amount: 0, totalEarned: 0, symbol: '🌀' },
    time: { id: 'time', name: 'Time Shards', amount: 0, totalEarned: 0, symbol: '⏳' },
    aether: { id: 'aether', name: 'Aether', amount: 0, totalEarned: 0, symbol: '💠' },
    entropy: { id: 'entropy', name: 'Entropy', amount: 0, totalEarned: 0, symbol: '🔥' },
  },
  upgrades: [
    {
      id: 'click_power',
      worldId: 'prime',
      name: 'Kinetic Capacitor',
      description: 'Increases Energy gained per click.',
      baseCost: 10,
      costMultiplier: 1.5,
      level: 0,
      effect: (l) => 1 + l * 3,
      type: 'click',
      resourceType: 'energy',
      targetResource: 'energy',
      unlockedAt: 0,
    },
    {
      id: 'solar_panel',
      worldId: 'prime',
      name: 'Solar Array',
      description: 'Basic photovoltaic cells that generate passive Energy.',
      baseCost: 15,
      costMultiplier: 1.15,
      level: 0,
      effect: (l) => l * 1,
      type: 'passive',
      resourceType: 'energy',
      targetResource: 'energy',
      unlockedAt: 0,
    },
    {
      id: 'geothermal_vent',
      worldId: 'prime',
      name: 'Geothermal Bore',
      description: 'Deep crust mining for stable heat energy.',
      baseCost: 120,
      costMultiplier: 1.15,
      level: 0,
      effect: (l) => l * 8,
      type: 'passive',
      resourceType: 'energy',
      targetResource: 'energy',
      unlockedAt: 100,
    },
    {
      id: 'fusion_core',
      worldId: 'prime',
      name: 'Fusion Reactor',
      description: 'Plasma confinement for massive Energy output.',
      baseCost: 1500,
      costMultiplier: 1.18,
      level: 0,
      effect: (l) => l * 65,
      type: 'passive',
      resourceType: 'energy',
      targetResource: 'energy',
      unlockedAt: 1000,
    },
    {
      id: 'dyson_swarm',
      worldId: 'prime',
      name: 'Dyson Swarm',
      description: 'Orbital mirror network harvesting an entire star.',
      baseCost: 35000,
      costMultiplier: 1.25,
      level: 0,
      effect: (l) => l * 450,
      type: 'passive',
      resourceType: 'energy',
      targetResource: 'energy',
      unlockedAt: 25000,
    },
    {
      id: 'matter_synth',
      worldId: 'prime',
      name: 'Matter Synthesizer',
      description: 'Condenses raw energy into hydrogen atoms.',
      baseCost: 800,
      costMultiplier: 1.2,
      level: 0,
      effect: (l) => l * 0.5,
      type: 'passive',
      resourceType: 'energy',
      targetResource: 'matter',
      unlockedAt: 500,
    },
    {
      id: 'molecular_printer',
      worldId: 'prime',
      name: 'Molecular Printer',
      description: 'Rapidly prints complex structures from energy.',
      baseCost: 7500,
      costMultiplier: 1.25,
      level: 0,
      effect: (l) => l * 6,
      type: 'passive',
      resourceType: 'energy',
      targetResource: 'matter',
      unlockedAt: 5000,
    },
    {
      id: 'silicon_miner',
      worldId: 'prime',
      name: 'Silicon Neural Net',
      description: 'Basic learning algorithms running on matter.',
      baseCost: 2500,
      costMultiplier: 1.22,
      level: 0,
      effect: (l) => l * 0.2,
      type: 'passive',
      resourceType: 'matter',
      targetResource: 'data',
      unlockedAt: 1000,
    },
    {
      id: 'quantum_computer',
      worldId: 'prime',
      name: 'Quantum Supercomputer',
      description: 'Exploits superposition for exponential processing.',
      baseCost: 25000,
      costMultiplier: 1.28,
      level: 0,
      effect: (l) => l * 3.5,
      type: 'passive',
      resourceType: 'matter',
      targetResource: 'data',
      unlockedAt: 10000,
    },
    {
      id: 'matrioshka_brain',
      worldId: 'prime',
      name: 'Matrioshka Brain',
      description: 'Converts a star system into a computer.',
      baseCost: 750000,
      costMultiplier: 1.4,
      level: 0,
      effect: (l) => l * 30,
      type: 'passive',
      resourceType: 'matter',
      targetResource: 'data',
      unlockedAt: 500000,
    },
    {
      id: 'void_siphon',
      worldId: 'prime',
      name: 'Void Siphon',
      description: 'Extracts exotic particles from the vacuum.',
      baseCost: 15000,
      costMultiplier: 1.5,
      level: 0,
      effect: (l) => l * 0.02,
      type: 'passive',
      resourceType: 'data',
      targetResource: 'stardust',
      unlockedAt: 5000,
    },
    {
      id: 'reality_engine',
      worldId: 'prime',
      name: 'Reality Engine',
      description: 'Rewrites physical laws to manifest stardust.',
      baseCost: 250000,
      costMultiplier: 1.6,
      level: 0,
      effect: (l) => l * 0.15,
      type: 'passive',
      resourceType: 'data',
      targetResource: 'stardust',
      unlockedAt: 100000,
    }
  ],
  lastSave: Date.now(),
  playTime: 0,
};